module.exports.descriptors = [
    'Miejski',
    'Starozytny',
    'Wodnisty',
    'Diamentowy',
    'Bursztynowy',
    'Kolorowy',
    'Mglisty',
    'Cichy',
    'Swietlisty',
    'Szybki',
    'Wielki',
    'Tani',
    'Zielony',
    'Wodnisty',
    'Drzewny',
    'Szybki',
    'Wiejski',
    'Polny'
]

module.exports.places = [
    'Pokoj',
    'Wioska',
    'Kanion',
    'Staw',
    'Oboz Grupowy',
    'Oboz Konny',
    'Oboz',
    'Oboz Harcerski',
    'Oboz Mysliwski',
    'Zatoka',
    'Miasto',
    'Miasteczko',
    'Piaski',
    'Odludzie',
    'Wyspa',
    'Wysepka',
    'Tunel',
    'Potok',
    'Oboz Lowiecki',
    'Las',
    'Wzgorze'
]